### ISSUE TITLE
Problem during Windows 7 compilation

### ISSUE THREAD

**Issue by sylvainpelissier** [CertiVox/MIRACL#11]
I tried to compile MIRACL library under Windows 7 64 bits with the following command as explained in the win64.txt file:

>ms64doit.bat

But I obtained the following message:
"copy mirdef.w64 mirdef.h The system cannot find the file specified."
It is strange since the file is located in "..\include", the script should move to this folder. But even doing this the script sould then include "mirdef.h" path in all following compilation commands.

**Comment by mcarrickscott** [comment]
You should unzip all of the miracle files into a single directory, with no
../include etc subfolders.

On Wed, Jul 22, 2015 at 12:35 PM, Sylvain Pelissier <
notifications@github.com> wrote:

> I tried to compile MIRACL library under Windows 7 64 bits with the
> following command as explained in the win64.txt file:
>
> ms64doit.bat
>
> But I obtained the following message:
> "copy mirdef.w64 mirdef.h The system cannot find the file specified."
> It is strange since the file is located in "..\include", the script should
> move to this folder. But even doing this the script sould then include
> "mirdef.h" path in all following compilation commands.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CertiVox/MIRACL/issues/11>.
>



-- 
Michael Scott
Chief Cryptographer
CertiVox Ltd
Tel (353) 86 3888746

"Those who give up essential security to purchase a slightly better user
experience, deserve to get hacked." (with apologies to Benjamin Franklin)

**Comment by sylvainpelissier** [comment]
Thank you it solve my problem.
