### ISSUE TITLE
OS X Compiling Issues

### ISSUE THREAD

**Issue by wankbank** [CertiVox/MIRACL#8]
Using OS X Yosemite 10.10.1 there are some problems when trying to compile. 

First using the Makefile:
```
$ make
gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh4.o mrflsh4.c
…
gcc -c -O2 -I. -I/usr/lib   -c -o mrcore.o mrcore.c
as   -o mrmuldv.o mrmuldv.s
ar crv miracl.a mrflsh4.o mrflsh3.o mrflsh2.o mrpi.o mrflsh1.o mrio2.o mrio1.o mrdouble.o mrflash.o mrrand.o mrprime.o mrcrt.o mrscrt.o mrfast.o mrjack.o mrfrnd.o mrxgcd.o mrgcd.o mrstrong.o mrbrick.o mrebrick.o mrcurve.o mrshs256.o mrshs512.o mrfpe.o mrsha3.o mrshs.o mraes.o mrgcm.o mrround.o mrbuild.o mrarth3.o mrbits.o mrarth2.o mrpower.o mrsroot.o mrec2m.o mrgf2m.o mrlucas.o mrzzn2.o mrzzn2b.o mrzzn3.o mrecn2.o mrmonty.o mralloc.o mrarth1.o mrarth0.o mrsmall.o mrcore.o mrmuldv.o 
r - mrflsh4.o
…
r - mrmuldv.o
gcc -c -O2 -I. -I/usr/lib   -c -o hail.o hail.c
make: *** No rule to make target `/usr/lib/libm.a', needed by `hail'.  Stop.
```

It seems to want to reference `libm.a` which is not an OS X library to my knowledge.

Next I tried to compile using the tips from the documentation:

```
$ gcc -c -O2 -I. -I/miracl.a hail.c -o hail
$ chmod +x hail
$ ./hail
-bash: ./hail: Malformed Mach-o file 
```

Not sure why things are getting malformed.

Lastly I tried omitting the `-c -O2` flags:

```
$ gcc -arch i386 -arch x86_64 -I. -I/miracl.a hail.c -o hail
Undefined symbols for architecture i386:
  "_copy", referenced from:
      _main in hail-8a8ae1.o
  "_incr", referenced from:
      _main in hail-8a8ae1.o
  "_innum", referenced from:
      _main in hail-8a8ae1.o
  "_mirsys", referenced from:
      _main in hail-8a8ae1.o
  "_mirvar", referenced from:
      _main in hail-8a8ae1.o
  "_mr_compare", referenced from:
      _main in hail-8a8ae1.o
  "_otnum", referenced from:
      _main in hail-8a8ae1.o
  "_premult", referenced from:
      _main in hail-8a8ae1.o
  "_size", referenced from:
      _main in hail-8a8ae1.o
  "_subdiv", referenced from:
      _main in hail-8a8ae1.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Regardless of whether it's `i386` or `x86_64` compiling without the flags always fails with undefined symbols.

Are there additional libraries that are required for `MIRACL` on OS X that I'm not aware of? I would really like to get this running, although I've come up empty.

**Comment by mcarrickscott** [comment]
Hmm. Don't have OS X here, and so I can't recreate the problem.. Clearly a
linker problem of some sort. Did you try including -lm on the command line?

If you Google for libm.a you will find a lot of people having problems
linking to libm.a - and some solutions.


Mike





On Fri, Jan 23, 2015 at 9:50 PM, wankbank <notifications@github.com> wrote:

> Using OS X Yosemite 10.10.1 there are some problems when trying to
> compile.
>
> First using the Makefile:
>
> $ make
> gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh4.o mrflsh4.c
> …
> gcc -c -O2 -I. -I/usr/lib   -c -o mrcore.o mrcore.c
> as   -o mrmuldv.o mrmuldv.s
> ar crv miracl.a mrflsh4.o mrflsh3.o mrflsh2.o mrpi.o mrflsh1.o mrio2.o mrio1.o mrdouble.o mrflash.o mrrand.o mrprime.o mrcrt.o mrscrt.o mrfast.o mrjack.o mrfrnd.o mrxgcd.o mrgcd.o mrstrong.o mrbrick.o mrebrick.o mrcurve.o mrshs256.o mrshs512.o mrfpe.o mrsha3.o mrshs.o mraes.o mrgcm.o mrround.o mrbuild.o mrarth3.o mrbits.o mrarth2.o mrpower.o mrsroot.o mrec2m.o mrgf2m.o mrlucas.o mrzzn2.o mrzzn2b.o mrzzn3.o mrecn2.o mrmonty.o mralloc.o mrarth1.o mrarth0.o mrsmall.o mrcore.o mrmuldv.o
> r - mrflsh4.o
> …
> r - mrmuldv.o
> gcc -c -O2 -I. -I/usr/lib   -c -o hail.o hail.c
> make: *** No rule to make target `/usr/lib/libm.a', needed by `hail'.  Stop.
>
> It seems to want to reference libm.a which is not an OS X library to my
> knowledge.
>
> Next I tried to compile using the tips from the documentation:
>
> $ gcc -c -O2 -I. -I/miracl.a hail.c -o hail
> $ chmod +x hail
> $ ./hail
> -bash: ./hail: Malformed Mach-o file
>
> Not sure why things are getting malformed.
>
> Lastly I tried omitting the -c -O2 flags:
>
> $ gcc -arch i386 -arch x86_64 -I. -I/miracl.a hail.c -o hail
> Undefined symbols for architecture i386:
>   "_copy", referenced from:
>       _main in hail-8a8ae1.o
>   "_incr", referenced from:
>       _main in hail-8a8ae1.o
>   "_innum", referenced from:
>       _main in hail-8a8ae1.o
>   "_mirsys", referenced from:
>       _main in hail-8a8ae1.o
>   "_mirvar", referenced from:
>       _main in hail-8a8ae1.o
>   "_mr_compare", referenced from:
>       _main in hail-8a8ae1.o
>   "_otnum", referenced from:
>       _main in hail-8a8ae1.o
>   "_premult", referenced from:
>       _main in hail-8a8ae1.o
>   "_size", referenced from:
>       _main in hail-8a8ae1.o
>   "_subdiv", referenced from:
>       _main in hail-8a8ae1.o
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>
> Regardless of whether it's i386 or x86_64 compiling with the flags always
> fails with missing symbols.
>
> Are there additional libraries that are required for MIRACL that I'm not
> aware of? I really like to get this running, although I've come up empty.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CertiVox/MIRACL/issues/8>.
>



-- 
Michael Scott
Chief Cryptographer
CertiVox Ltd
Tel (353) 86 3888746

**Comment by wankbank** [comment]
Using `-lm` unfortunately resulted in:
```
clang: warning: -lm: 'linker' input unused
```
`libm.a` does not exist OS X.

From my understanding OS X uses dynamic libraries, but I'm at a loss on how to get this working. Please get Mac so you can help me! :/

**Comment by mcarrickscott** [comment]
Try commenting out the reference to libm.a in the make file

Mike

On Wednesday, January 28, 2015, wankbank <notifications@github.com> wrote:

> Using -lm unfortunately resulted in:
>
> clang: warning: -lm: 'linker' input unused
>
> libm.a does not exist OS X.
>
> From my understanding OS X uses dynamic libraries, but I'm at a loss on
> how to get this working. Please get Mac so you can help me! :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CertiVox/MIRACL/issues/8#issuecomment-71908805>.
>


-- 
Michael Scott
Chief Cryptographer
CertiVox Ltd
Tel (353) 86 3888746

**Comment by wankbank** [comment]
Thank you for the quick response; using only `LIBS = miracl.a`:
```
$ make
gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh4.o mrflsh4.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh3.o mrflsh3.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh2.o mrflsh2.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrpi.o mrpi.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh1.o mrflsh1.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrio2.o mrio2.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrio1.o mrio1.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrdouble.o mrdouble.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrflash.o mrflash.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrrand.o mrrand.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrprime.o mrprime.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrcrt.o mrcrt.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrscrt.o mrscrt.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrfast.o mrfast.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrjack.o mrjack.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrfrnd.o mrfrnd.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrxgcd.o mrxgcd.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrgcd.o mrgcd.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrstrong.o mrstrong.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrbrick.o mrbrick.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrebrick.o mrebrick.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrcurve.o mrcurve.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrshs256.o mrshs256.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrshs512.o mrshs512.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrfpe.o mrfpe.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrsha3.o mrsha3.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrshs.o mrshs.c
gcc -c -O2 -I. -I/usr/lib   -c -o mraes.o mraes.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrgcm.o mrgcm.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrround.o mrround.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrbuild.o mrbuild.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrarth3.o mrarth3.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrbits.o mrbits.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrarth2.o mrarth2.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrpower.o mrpower.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrsroot.o mrsroot.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrec2m.o mrec2m.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrgf2m.o mrgf2m.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrlucas.o mrlucas.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrzzn2.o mrzzn2.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrzzn2b.o mrzzn2b.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrzzn3.o mrzzn3.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrecn2.o mrecn2.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrmonty.o mrmonty.c
gcc -c -O2 -I. -I/usr/lib   -c -o mralloc.o mralloc.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrarth1.o mrarth1.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrarth0.o mrarth0.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrsmall.o mrsmall.c
gcc -c -O2 -I. -I/usr/lib   -c -o mrcore.o mrcore.c
ar crv miracl.a mrflsh4.o mrflsh3.o mrflsh2.o mrpi.o mrflsh1.o mrio2.o mrio1.o mrdouble.o mrflash.o mrrand.o mrprime.o mrcrt.o mrscrt.o mrfast.o mrjack.o mrfrnd.o mrxgcd.o mrgcd.o mrstrong.o mrbrick.o mrebrick.o mrcurve.o mrshs256.o mrshs512.o mrfpe.o mrsha3.o mrshs.o mraes.o mrgcm.o mrround.o mrbuild.o mrarth3.o mrbits.o mrarth2.o mrpower.o mrsroot.o mrec2m.o mrgf2m.o mrlucas.o mrzzn2.o mrzzn2b.o mrzzn3.o mrecn2.o mrmonty.o mralloc.o mrarth1.o mrarth0.o mrsmall.o mrcore.o mrmuldv.o 
r - mrflsh4.o
r - mrflsh3.o
r - mrflsh2.o
r - mrpi.o
r - mrflsh1.o
r - mrio2.o
r - mrio1.o
r - mrdouble.o
r - mrflash.o
r - mrrand.o
r - mrprime.o
r - mrcrt.o
r - mrscrt.o
r - mrfast.o
r - mrjack.o
r - mrfrnd.o
r - mrxgcd.o
r - mrgcd.o
r - mrstrong.o
r - mrbrick.o
r - mrebrick.o
r - mrcurve.o
r - mrshs256.o
r - mrshs512.o
r - mrfpe.o
r - mrsha3.o
r - mrshs.o
r - mraes.o
r - mrgcm.o
r - mrround.o
r - mrbuild.o
r - mrarth3.o
r - mrbits.o
r - mrarth2.o
r - mrpower.o
r - mrsroot.o
r - mrec2m.o
r - mrgf2m.o
r - mrlucas.o
r - mrzzn2.o
r - mrzzn2b.o
r - mrzzn3.o
r - mrecn2.o
r - mrmonty.o
r - mralloc.o
r - mrarth1.o
r - mrarth0.o
r - mrsmall.o
r - mrcore.o
r - mrmuldv.o
/opt/local/bin/ranlib: file: miracl.a(mrflsh4.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrflsh3.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrflsh2.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrpi.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrflsh1.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrdouble.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrflash.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrfrnd.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrround.o) has no symbols
/opt/local/bin/ranlib: file: miracl.a(mrbuild.o) has no symbols
gcc -c -O2 -I. -I/usr/lib   -c -o hail.o hail.c
gcc -o hail hail.o 
Undefined symbols for architecture x86_64:
  "_copy", referenced from:
      _main in hail.o
  "_incr", referenced from:
      _main in hail.o
  "_innum", referenced from:
      _main in hail.o
  "_mirsys", referenced from:
      _main in hail.o
  "_mirvar", referenced from:
      _main in hail.o
  "_mr_compare", referenced from:
      _main in hail.o
  "_otnum", referenced from:
      _main in hail.o
  "_premult", referenced from:
      _main in hail.o
  "_size", referenced from:
      _main in hail.o
  "_subdiv", referenced from:
      _main in hail.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hail] Error 1
```

I tried using the `-shared` flag with `flat-namespace`:
```
$ cc -shared -flat_namespace -undefined suppress pk-demo.c miracl.a -o pk-demo.o
$ gcc pk-demo.o miracl.a -o pk-demo
$ ./pk-demo
First Diffie-Hellman Key exchange .... 

Alice's offline calculation
dyld: lazy symbol binding failed: Symbol not found: _kcm_sqr
  Referenced from: pk-demo.o
  Expected in: flat namespace

dyld: Symbol not found: _kcm_sqr
  Referenced from: pk-demo.o
  Expected in: flat namespace

Trace/BPT trap: 5
```

**Comment by mcarrickscott** [comment]
Well I think

gcc -o hail hail.o

otherwise there is no linkage to the miracl library (hence the undefined
symbols). It should be

gcc hail.o miracl.a -o hail

Also this

Symbol not found: _kcm_sqr

would suggest that you have defined MR_KCM in mirdef.h

The make file does not support the more elaborate build options of the
library (the module mrkcm.o would be missing), so I suggest you start
with the basic mirdef.h file.


Mike

On Wed, Jan 28, 2015 at 9:28 PM, wankbank <notifications@github.com> wrote:

> Thank you for the quick response; using only LIBS = miracl.a:
>
> $ make
> gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh4.o mrflsh4.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh3.o mrflsh3.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh2.o mrflsh2.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrpi.o mrpi.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrflsh1.o mrflsh1.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrio2.o mrio2.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrio1.o mrio1.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrdouble.o mrdouble.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrflash.o mrflash.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrrand.o mrrand.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrprime.o mrprime.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrcrt.o mrcrt.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrscrt.o mrscrt.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrfast.o mrfast.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrjack.o mrjack.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrfrnd.o mrfrnd.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrxgcd.o mrxgcd.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrgcd.o mrgcd.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrstrong.o mrstrong.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrbrick.o mrbrick.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrebrick.o mrebrick.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrcurve.o mrcurve.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrshs256.o mrshs256.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrshs512.o mrshs512.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrfpe.o mrfpe.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrsha3.o mrsha3.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrshs.o mrshs.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mraes.o mraes.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrgcm.o mrgcm.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrround.o mrround.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrbuild.o mrbuild.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrarth3.o mrarth3.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrbits.o mrbits.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrarth2.o mrarth2.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrpower.o mrpower.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrsroot.o mrsroot.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrec2m.o mrec2m.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrgf2m.o mrgf2m.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrlucas.o mrlucas.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrzzn2.o mrzzn2.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrzzn2b.o mrzzn2b.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrzzn3.o mrzzn3.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrecn2.o mrecn2.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrmonty.o mrmonty.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mralloc.o mralloc.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrarth1.o mrarth1.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrarth0.o mrarth0.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrsmall.o mrsmall.c
> gcc -c -O2 -I. -I/usr/lib   -c -o mrcore.o mrcore.c
> ar crv miracl.a mrflsh4.o mrflsh3.o mrflsh2.o mrpi.o mrflsh1.o mrio2.o mrio1.o mrdouble.o mrflash.o mrrand.o mrprime.o mrcrt.o mrscrt.o mrfast.o mrjack.o mrfrnd.o mrxgcd.o mrgcd.o mrstrong.o mrbrick.o mrebrick.o mrcurve.o mrshs256.o mrshs512.o mrfpe.o mrsha3.o mrshs.o mraes.o mrgcm.o mrround.o mrbuild.o mrarth3.o mrbits.o mrarth2.o mrpower.o mrsroot.o mrec2m.o mrgf2m.o mrlucas.o mrzzn2.o mrzzn2b.o mrzzn3.o mrecn2.o mrmonty.o mralloc.o mrarth1.o mrarth0.o mrsmall.o mrcore.o mrmuldv.o
> r - mrflsh4.o
> r - mrflsh3.o
> r - mrflsh2.o
> r - mrpi.o
> r - mrflsh1.o
> r - mrio2.o
> r - mrio1.o
> r - mrdouble.o
> r - mrflash.o
> r - mrrand.o
> r - mrprime.o
> r - mrcrt.o
> r - mrscrt.o
> r - mrfast.o
> r - mrjack.o
> r - mrfrnd.o
> r - mrxgcd.o
> r - mrgcd.o
> r - mrstrong.o
> r - mrbrick.o
> r - mrebrick.o
> r - mrcurve.o
> r - mrshs256.o
> r - mrshs512.o
> r - mrfpe.o
> r - mrsha3.o
> r - mrshs.o
> r - mraes.o
> r - mrgcm.o
> r - mrround.o
> r - mrbuild.o
> r - mrarth3.o
> r - mrbits.o
> r - mrarth2.o
> r - mrpower.o
> r - mrsroot.o
> r - mrec2m.o
> r - mrgf2m.o
> r - mrlucas.o
> r - mrzzn2.o
> r - mrzzn2b.o
> r - mrzzn3.o
> r - mrecn2.o
> r - mrmonty.o
> r - mralloc.o
> r - mrarth1.o
> r - mrarth0.o
> r - mrsmall.o
> r - mrcore.o
> r - mrmuldv.o
> /opt/local/bin/ranlib: file: miracl.a(mrflsh4.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrflsh3.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrflsh2.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrpi.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrflsh1.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrdouble.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrflash.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrfrnd.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrround.o) has no symbols
> /opt/local/bin/ranlib: file: miracl.a(mrbuild.o) has no symbols
> gcc -c -O2 -I. -I/usr/lib   -c -o hail.o hail.c
> gcc -o hail hail.o
> Undefined symbols for architecture x86_64:
>   "_copy", referenced from:
>       _main in hail.o
>   "_incr", referenced from:
>       _main in hail.o
>   "_innum", referenced from:
>       _main in hail.o
>   "_mirsys", referenced from:
>       _main in hail.o
>   "_mirvar", referenced from:
>       _main in hail.o
>   "_mr_compare", referenced from:
>       _main in hail.o
>   "_otnum", referenced from:
>       _main in hail.o
>   "_premult", referenced from:
>       _main in hail.o
>   "_size", referenced from:
>       _main in hail.o
>   "_subdiv", referenced from:
>       _main in hail.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [hail] Error 1
>
> I tried using the -shared flag with flat-namespace:
>
> $ cc -shared -flat_namespace -undefined suppress pk-demo.c miracl.a -o pk-demo.o
> $ gcc pk-demo.o miracl.a -o pk-demo
> $ ./pk-demo
> First Diffie-Hellman Key exchange ....
>
> Alice's offline calculation
> dyld: lazy symbol binding failed: Symbol not found: _kcm_sqr
>   Referenced from: pk-demo.o
>   Expected in: flat namespace
>
> dyld: Symbol not found: _kcm_sqr
>   Referenced from: pk-demo.o
>   Expected in: flat namespace
>
> Trace/BPT trap: 5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CertiVox/MIRACL/issues/8#issuecomment-71919932>.
>



-- 
Michael Scott
Chief Cryptographer
CertiVox Ltd
Tel (353) 86 3888746

**Comment by wankbank** [comment]
Thank you so very much!
```
gcc hail.o miracl.a -o hail
```
This is what I had failed to do. `hail.o` compiled using that, and executed fine. I'm very happy that I can start exploring this amazing SDK. Again, I really appreciate your help — you're a gentlemen and a scholar (obviously) :)
