### ISSUE TITLE
generating primes with nxprime

### ISSUE THREAD

**Issue by sumproxy** [CertiVox/MIRACL#9]
I'm trying to test the compiled miracl.a with the following cpp code:
```
extern "C" {
  #include "miracl.h"
  #include <stdio.h>
}
extern BOOL  nxprime(_MIPT_ big,big);
extern flash mirvar(_MIPD_ int iv);
extern miracl *mirsys(int,mr_small);

#include <iostream>


int main() {
  big a;
  miracl *mip = mirsys(5000,10);
  a = mirvar(5);
  std::cout << a->len << std::endl;
}

```

I get the following compiler output
```
g++ -m64 -O2 __test__.cpp miracl.a -o test
Undefined symbols for architecture x86_64:
  "_mirsys", referenced from:
      _main in __test__-1328d4.o
  "_mirvar", referenced from:
      _main in __test__-1328d4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Please help can't figure out how to use nxprime
Here's the question on StackOverflow https://stackoverflow.com/questions/31218430/generating-primes-with-nxprime

**Comment by mcarrickscott** [comment]
Problem is you are mixing C++ and C

You need to google for “name mangling”. I couldn’t really explain by email

I would suggest that you work in C++ and use the function “nextprime” you can see in big.h 

Look at the example C++ programs that compiled successfully in linux64, and use them as a model for developing your own program.



Mike

**Comment by sumproxy** [comment]
Thanks for help!

04 июля 2015 г., в 12:26, mcarrickscott <notifications@github.com> написал(а):

> Problem is you are mixing C++ and C
> 
> You need to google for “name mangling”. I couldn’t really explain by email
> 
> I would suggest that you work in C++ and use the function “nextprime” you can see in big.h 
> 
> Look at the example C++ programs that compiled successfully in linux64, and use them as a model for developing your own program.
> 
> 
> 
> Mike
>

**Comment by sumproxy** [comment]
Thanks again for all your help. I got another question: is it possible to initialize Big’s from argv arguments. I tried using string stream, but it fails…

Thanks

04 июля 2015 г., в 12:26, mcarrickscott <notifications@github.com> написал(а):

> Problem is you are mixing C++ and C
> 
> You need to google for “name mangling”. I couldn’t really explain by email
> 
> I would suggest that you work in C++ and use the function “nextprime” you can see in big.h 
> 
> Look at the example C++ programs that compiled successfully in linux64, and use them as a model for developing your own program.
> 
> 
> 
> Mike
>

**Comment by mcarrickscott** [comment]
// gcc -O2 sum.cpp big.cpp miracl.a -o sum
// sum 12121212121212121

#include <iostream>
#include "big.h"

using namespace std;

Miracl precision=1000;

int main(int argc,char **argv)
{
    Big x=argv[1];
    cout << "x= " << x << endl;
    return 0;
}



On Mon, Jul 6, 2015 at 12:07 PM, Sum Proxy <notifications@github.com> wrote:

> Thanks again for all your help. I got another question: is it possible to
> initialize Big’s from argv arguments. I tried using string stream, but it
> fails…
>
> Thanks
>
> 04 июля 2015 г., в 12:26, mcarrickscott <notifications@github.com>
> написал(а):
>
> > Problem is you are mixing C++ and C
> >
> > You need to google for “name mangling”. I couldn’t really explain by
> email
> >
> > I would suggest that you work in C++ and use the function “nextprime”
> you can see in big.h
> >
> > Look at the example C++ programs that compiled successfully in linux64,
> and use them as a model for developing your own program.
> >
> >
> >
> > Mike
> >
> > > On 4 Jul 2015, at 08:43, Sum Proxy <notifications@github.com> wrote:
> > >
> > > I'm trying to test the compiled miracl.a with the following cpp code:
> > >
> > > extern "C" {
> > > #include "miracl.h"
> > > #include <stdio.h>
> > > }
> > > extern BOOL nxprime(_MIPT_ big,big);
> > > extern flash mirvar(_MIPD_ int iv);
> > > extern miracl *mirsys(int,mr_small);
> > >
> > > #include <iostream>
> > >
> > >
> > > int main() {
> > > big a;
> > > miracl *mip = mirsys(5000,10);
> > > a = mirvar(5);
> > > std::cout << a->len << std::endl;
> > > }
> > >
> > > I get the following compiler output
> > >
> > > g++ -m64 -O2 __test__.cpp miracl.a -o test
> > > Undefined symbols for architecture x86_64:
> > > "_mirsys", referenced from:
> > > _main in __test__-1328d4.o
> > > "_mirvar", referenced from:
> > > _main in __test__-1328d4.o
> > > ld: symbol(s) not found for architecture x86_64
> > > clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
> > > Please help can't figure out how to use nxprime
> > >
> > > —
> > > Reply to this email directly or view it on GitHub <
> https://github.com/CertiVox/MIRACL/issues/9>.
>
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CertiVox/MIRACL/issues/9#issuecomment-118818383>.
>



-- 
Michael Scott
Chief Cryptographer
CertiVox Ltd
Tel (353) 86 3888746

"Those who give up essential security to purchase a slightly better user
experience, deserve to get hacked."

**Comment by mcarrickscott** [comment]
Whoops, that should be g++, not gcc

Mike

On Mon, Jul 6, 2015 at 12:46 PM, Michael Scott <mike.scott@certivox.com>
wrote:

> // gcc -O2 sum.cpp big.cpp miracl.a -o sum
> // sum 12121212121212121
>
> #include <iostream>
> #include "big.h"
>
> using namespace std;
>
> Miracl precision=1000;
>
> int main(int argc,char **argv)
> {
>     Big x=argv[1];
>     cout << "x= " << x << endl;
>     return 0;
> }
>
>
>
> On Mon, Jul 6, 2015 at 12:07 PM, Sum Proxy <notifications@github.com>
> wrote:
>
>> Thanks again for all your help. I got another question: is it possible to
>> initialize Big’s from argv arguments. I tried using string stream, but it
>> fails…
>>
>> Thanks
>>
>> 04 июля 2015 г., в 12:26, mcarrickscott <notifications@github.com>
>> написал(а):
>>
>> > Problem is you are mixing C++ and C
>> >
>> > You need to google for “name mangling”. I couldn’t really explain by
>> email
>> >
>> > I would suggest that you work in C++ and use the function “nextprime”
>> you can see in big.h
>> >
>> > Look at the example C++ programs that compiled successfully in linux64,
>> and use them as a model for developing your own program.
>> >
>> >
>> >
>> > Mike
>> >
>> > > On 4 Jul 2015, at 08:43, Sum Proxy <notifications@github.com> wrote:
>> > >
>> > > I'm trying to test the compiled miracl.a with the following cpp code:
>> > >
>> > > extern "C" {
>> > > #include "miracl.h"
>> > > #include <stdio.h>
>> > > }
>> > > extern BOOL nxprime(_MIPT_ big,big);
>> > > extern flash mirvar(_MIPD_ int iv);
>> > > extern miracl *mirsys(int,mr_small);
>> > >
>> > > #include <iostream>
>> > >
>> > >
>> > > int main() {
>> > > big a;
>> > > miracl *mip = mirsys(5000,10);
>> > > a = mirvar(5);
>> > > std::cout << a->len << std::endl;
>> > > }
>> > >
>> > > I get the following compiler output
>> > >
>> > > g++ -m64 -O2 __test__.cpp miracl.a -o test
>> > > Undefined symbols for architecture x86_64:
>> > > "_mirsys", referenced from:
>> > > _main in __test__-1328d4.o
>> > > "_mirvar", referenced from:
>> > > _main in __test__-1328d4.o
>> > > ld: symbol(s) not found for architecture x86_64
>> > > clang: error: linker command failed with exit code 1 (use -v to see
>> invocation)
>> > > Please help can't figure out how to use nxprime
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub <
>> https://github.com/CertiVox/MIRACL/issues/9>.
>>
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CertiVox/MIRACL/issues/9#issuecomment-118818383>.
>>
>
>
>
> --
> Michael Scott
> Chief Cryptographer
> CertiVox Ltd
> Tel (353) 86 3888746
>
> "Those who give up essential security to purchase a slightly better user
> experience, deserve to get hacked."
>
>


-- 
Michael Scott
Chief Cryptographer
CertiVox Ltd
Tel (353) 86 3888746

"Those who give up essential security to purchase a slightly better user
experience, deserve to get hacked."

**Comment by sumproxy** [comment]
I can’t believe it’s that simple!
Thanks again!

06 июля 2015 г., в 14:49, mcarrickscott <notifications@github.com> написал(а):

> Whoops, that should be g++, not gcc
> 
> Mike
> 
> On Mon, Jul 6, 2015 at 12:46 PM, Michael Scott <mike.scott@certivox.com>
> wrote:
> 
> > // gcc -O2 sum.cpp big.cpp miracl.a -o sum
> > // sum 12121212121212121
> >
> > #include <iostream>
> > #include "big.h"
> >
> > using namespace std;
> >
> > Miracl precision=1000;
> >
> > int main(int argc,char **argv)
> > {
> > Big x=argv[1];
> > cout << "x= " << x << endl;
> > return 0;
> > }
> >
> >
> >
> > On Mon, Jul 6, 2015 at 12:07 PM, Sum Proxy <notifications@github.com>
> > wrote:
> >
> >> Thanks again for all your help. I got another question: is it possible to
> >> initialize Big’s from argv arguments. I tried using string stream, but it
> >> fails…
> >>
> >> Thanks
> >>
> >> 04 июля 2015 г., в 12:26, mcarrickscott <notifications@github.com>
> >> написал(а):
> >>
> >> > Problem is you are mixing C++ and C
> >> >
> >> > You need to google for “name mangling”. I couldn’t really explain by
> >> email
> >> >
> >> > I would suggest that you work in C++ and use the function “nextprime”
> >> you can see in big.h
> >> >
> >> > Look at the example C++ programs that compiled successfully in linux64,
> >> and use them as a model for developing your own program.
> >> >
> >> >
> >> >
> >> > Mike
> >> >

**Comment by sumproxy** [comment]
Sorry to bother you again, but how can I find out if a Float represents and integral value using MIRACL
Thanks!

06 июля 2015 г., в 14:49, mcarrickscott <notifications@github.com> написал(а):

> Whoops, that should be g++, not gcc
> 
> Mike
> 
> On Mon, Jul 6, 2015 at 12:46 PM, Michael Scott <mike.scott@certivox.com>
> wrote:
> 
> > // gcc -O2 sum.cpp big.cpp miracl.a -o sum
> > // sum 12121212121212121
> >
> > #include <iostream>
> > #include "big.h"
> >
> > using namespace std;
> >
> > Miracl precision=1000;
> >
> > int main(int argc,char **argv)
> > {
> > Big x=argv[1];
> > cout << "x= " << x << endl;
> > return 0;
> > }
> >
> >
> >
> > On Mon, Jul 6, 2015 at 12:07 PM, Sum Proxy <notifications@github.com>
> > wrote:
> >
> >> Thanks again for all your help. I got another question: is it possible to
> >> initialize Big’s from argv arguments. I tried using string stream, but it
> >> fails…
> >>
> >> Thanks
> >>
> >> 04 июля 2015 г., в 12:26, mcarrickscott <notifications@github.com>
> >> написал(а):
> >>
> >> > Problem is you are mixing C++ and C
> >> >
> >> > You need to google for “name mangling”. I couldn’t really explain by
> >> email
> >> >
> >> > I would suggest that you work in C++ and use the function “nextprime”
> >> you can see in big.h
> >> >
> >> > Look at the example C++ programs that compiled successfully in linux64,
> >> and use them as a model for developing your own program.
> >> >
> >> >
> >> >
> >> > Mike
> >> >
